backend:
  name: git-gateway

media_folder: static/assets

collections:
  - name: page
    label: Page
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }